name: Build an angular project
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        - name: push to heroku
          env :
            HEROKU_REGISTRY_URL: registry.heroku.com
            HEROKU_TOKEN : ${{ secrets.HEROKU_TOKEN }}
            APP_NAME : ${{ secrets.APP_NAME }}
          run : |
            docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
            export HEROKU_API_KEY=$HEROKU_TOKEN
            heroku container:login
            heroku container:push web --app $APP_NAME
            heroku container:release web --app $APP_NAME
            heroku ps:scale web=1 --app $APP_NAME

